# Generated by Django 4.2.1 on 2023-05-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.TextField(choices=[('open', 'Открыто'), ('close', 'Закрыто')], default='open'),
        ),
    ]
